/**
 * Golden tests (testing-strategy.md): human-verified input → expected fixtures
 * in golden/. Expectations were generated by an independent Python
 * implementation of data-model.md §Tax computation, so this suite is a
 * cross-implementation check, not a tautology. Changing any expected value
 * requires explicit review.
 */
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import {
  calculateCart,
  calculateLineTax,
  type CartInput,
  type CartTotals,
  type PriceMode,
  type TaxLine,
  type TaxRate,
} from '../src/index.js';

interface TaxCase {
  name: string;
  taxableAmount: number;
  rates: TaxRate[];
  mode: PriceMode;
  expected: TaxLine[];
}

interface CartCase {
  name: string;
  input: CartInput;
  expected: CartTotals;
}

function loadGolden<T>(file: string): T {
  return JSON.parse(readFileSync(new URL(`../golden/${file}`, import.meta.url), 'utf8')) as T;
}

const taxFixture = loadGolden<{ cases: TaxCase[] }>('tax-cases.json');
const cartFixture = loadGolden<{ cases: CartCase[] }>('cart-cases.json');

describe('golden: tax engine', () => {
  it('has enough cases to matter', () => {
    expect(taxFixture.cases.length + cartFixture.cases.length).toBeGreaterThanOrEqual(40);
  });

  for (const c of taxFixture.cases) {
    it(c.name, () => {
      expect(calculateLineTax(c.taxableAmount, c.rates, c.mode)).toEqual(c.expected);
    });
  }
});

describe('golden: cart calculator', () => {
  for (const c of cartFixture.cases) {
    it(c.name, () => {
      expect(calculateCart(c.input)).toEqual(c.expected);
    });
  }
});
